import { useEffect, useMemo, useState } from 'react'
import { SlidersHorizontal, Check, Search, X, RefreshCw, EyeOff } from 'lucide-react'
import Header from '../components/Header'
import DealCard from '../components/DealCard'
import { categories, taxonomy, seasons, occasions } from '../lib/taxonomy'
import { loadLiveDeals, formatScanTime } from '../lib/deals'
import { supabase } from '../lib/supabase'
import { runRetailerScan } from '../lib/productImport'
import { useAuth } from '../context/AuthContext'
import { useSearchParams } from 'react-router-dom'

const quick=['Great Value','50%+ Off','70%+ Off','New','Verified Size','Church','Everyday','Fall','Lowest Seen','Watched']; const sortTabs=['Best for Hollie','Best Value','Deepest Discounts','Lowest Price','Newest']
export default function Deals(){
 const {session}=useAuth(); const [searchParams]=useSearchParams(); const [hidden,setHidden]=useState(new Set()); const [feedbackDeal,setFeedbackDeal]=useState(null); const [scanBusy,setScanBusy]=useState(false); const [scanMessage,setScanMessage]=useState(''); const [allDeals,setAllDeals]=useState([]); const [lastScan,setLastScan]=useState(null); const [watched,setWatched]=useState(new Set()); const [profileId,setProfileId]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 const [category,setCategory]=useState('All'),[subcategory,setSubcategory]=useState('All'),[quickFilters,setQuickFilters]=useState([]),[sortBy,setSortBy]=useState('Best for Hollie'),[q,setQ]=useState(''),[filtersOpen,setFiltersOpen]=useState(false),[season,setSeason]=useState('Any'),[occasion,setOccasion]=useState('Any'),[minDiscount,setMinDiscount]=useState(0)
 useEffect(()=>{const quick=searchParams.get('quick'),quality=searchParams.get('quality'),cat=searchParams.get('category'),store=searchParams.get('store');if(quick)setQuickFilters([quick]);if(quality==='Exceptional')setQuickFilters(['Exceptional']);if(cat)setCategory(cat);if(store)setQ(store)},[searchParams])
 const scanNow=async()=>{setScanBusy(true);setScanMessage('Checking retailer sale pages, products, prices, and Hollie’s exact sizes…');try{const r=await runRetailerScan();const rows=r.summary||[];const checked=rows.reduce((a,x)=>a+(x.checked||0),0),found=rows.reduce((a,x)=>a+(x.deals||0),0),sizeVerified=rows.reduce((a,x)=>a+(x.sizeVerified||0),0),failed=rows.filter(x=>x?.error||x?.errors>0&&!x?.checked).length,completed=Math.max(0,rows.length-failed);setScanMessage(`${failed?'Scan finished with some retailer errors':'Scan complete'} · ${completed}/${rows.length} retailers updated · ${found} deals · ${sizeVerified} exact-size verifications · ${checked} products checked.${failed?' Successful stores were still saved.':' Full retailer health is in Settings.'}`);await load()}catch(e){setScanMessage(e.message)}finally{setScanBusy(false)}}
 const load=async()=>{setLoading(true);setError(''); const {deals,lastScan,error}=await loadLiveDeals(session?.user?.id); if(error){setError(allDeals.length?'Couldn’t refresh — showing your last verified deals.':'Couldn’t load verified deals. Try Refresh again.')}else{setAllDeals(deals);setLastScan(lastScan)}
   if(session?.user?.id){const [{data:p},{data:w},{data:f}]=await Promise.all([supabase.from('fh_profiles').select('id').eq('owner_user_id',session.user.id).single(),supabase.from('fh_watchlist').select('product_id').eq('owner_user_id',session.user.id).eq('active',true),supabase.from('fh_deal_feedback').select('product_id').eq('owner_user_id',session.user.id).eq('suppress',true)]);setProfileId(p?.id||null);setWatched(new Set((w||[]).map(x=>x.product_id)));setHidden(new Set((f||[]).map(x=>x.product_id)))} setLoading(false)}
 useEffect(()=>{load()},[session?.user?.id])
 const toggleQuick=n=>setQuickFilters(p=>p.includes(n)?p.filter(x=>x!==n):[...p,n]); const resetAll=()=>{setCategory('All');setSubcategory('All');setQuickFilters([]);setSeason('Any');setOccasion('Any');setMinDiscount(0);setQ('')}
 const filtered=useMemo(()=>{let rows=allDeals.filter(d=>{if(hidden.has(d.productId))return false;if(category!=='All'&&d.category!==category)return false;if(subcategory!=='All'&&d.subcategory!==subcategory)return false;if(season!=='Any'&&!(d.season||[]).includes(season))return false;if(occasion!=='Any'&&!(d.occasion||[]).includes(occasion))return false;if(d.discount<minDiscount)return false;if(q&&!`${d.store} ${d.name} ${d.category} ${d.subcategory}`.toLowerCase().includes(q.toLowerCase()))return false;if(quickFilters.includes('Exceptional')&&d.badge!=='Exceptional')return false;if(quickFilters.includes('Great Value')&&(d.valueScore||d.match||0)<75)return false;if(quickFilters.includes('50%+ Off')&&d.discount<50)return false;if(quickFilters.includes('70%+ Off')&&d.discount<70)return false;if(quickFilters.includes('New')&&!d.newDeal)return false;if(quickFilters.includes('Verified Size')&&!d.verified)return false;if(quickFilters.includes('Church')&&!d.occasion.includes('Church'))return false;if(quickFilters.includes('Everyday')&&!d.occasion.includes('Everyday'))return false;if(quickFilters.includes('Fall')&&!d.season.includes('Fall'))return false;if(quickFilters.includes('Lowest Seen')&&!d.lowestSeen)return false;if(quickFilters.includes('Watched')&&!watched.has(d.productId))return false;return true}); if(sortBy==='Best Value')rows=[...rows].sort((a,b)=>(b.valueScore||b.match||0)-(a.valueScore||a.match||0)||a.sale-b.sale);else if(sortBy==='Deepest Discounts')rows=[...rows].sort((a,b)=>b.discount-a.discount);else if(sortBy==='Lowest Price')rows=[...rows].sort((a,b)=>a.sale-b.sale);else if(sortBy==='Newest')rows=[...rows].sort((a,b)=>Number(b.newDeal)-Number(a.newDeal)||b.discount-a.discount);else {const priority=d=>{const t=`${d.name||''} ${d.subcategory||''}`.toLowerCase();return (/jean|denim/.test(t)&&d.category==='Bottoms'?35:0)+(/cardigan|duster|sweater|jacket/.test(t)&&d.category==='Layers'?30:0)};rows=[...rows].sort((a,b)=>((b.match||0)+priority(b))-((a.match||0)+priority(a))||b.discount-a.discount);}return rows},[allDeals,hidden,watched,category,subcategory,season,occasion,minDiscount,q,quickFilters,sortBy])
 const toggleWatch=async deal=>{if(!session?.user?.id||!profileId||!deal.productId){setScanMessage('Watch could not be saved. Profile or product information is missing.');return;} if(watched.has(deal.productId)){await supabase.from('fh_watchlist').update({active:false}).eq('owner_user_id',session.user.id).eq('product_id',deal.productId);setWatched(p=>{const n=new Set(p);n.delete(deal.productId);return n})}else{const {data:existing}=await supabase.from('fh_watchlist').select('id').eq('owner_user_id',session.user.id).eq('product_id',deal.productId).maybeSingle();let error;if(existing?.id){({error}=await supabase.from('fh_watchlist').update({variant_id:deal.variantId||null,watch_price:deal.sale,watch_size:deal.size,price_drop_alert:true,restock_alert:true,lowest_price_alert:true,active:true}).eq('id',existing.id))}else{({error}=await supabase.from('fh_watchlist').insert({owner_user_id:session.user.id,profile_id:profileId,product_id:deal.productId,variant_id:deal.variantId||null,watch_price:deal.sale,watch_size:deal.size,price_drop_alert:true,restock_alert:true,lowest_price_alert:true,active:true}))}if(!error)setWatched(p=>new Set([...p,deal.productId]));else setScanMessage(`Watch could not be saved: ${error.message}`)}}

 const rejectDeal=async(reason)=>{const deal=feedbackDeal;if(!deal||!session?.user?.id||!deal.productId)return;const row={owner_user_id:session.user.id,profile_id:profileId,product_id:deal.productId,variant_id:deal.variantId||null,deal_id:deal.id||null,reason,suppress:true,updated_at:new Date().toISOString()};const {error}=await supabase.from('fh_deal_feedback').upsert(row,{onConflict:'owner_user_id,product_id,variant_id'});if(!error){setHidden(p=>new Set([...p,deal.productId]));setFeedbackDeal(null);setScanMessage('Deal removed. Your feedback was saved.')}else{setScanMessage(`Feedback could not be saved: ${error.message}`);setFeedbackDeal(null)}}
 const activeCount=quickFilters.length+(category!=='All')+(subcategory!=='All')+(season!=='Any')+(occasion!=='Any')+(minDiscount?1:0); const subs=category==='All'?[]:(taxonomy[category]||[])
 return <main className="page"><Header title="Deals" subtitle="Verified discounts in Hollie's exact size."/>
   <section className="update-strip"><div><Check size={16}/><strong>Verified feed</strong> · {formatScanTime(lastScan)}</div><div className="scan-actions"><button className="text-action" onClick={load}><RefreshCw size={14}/> Refresh</button><button className="text-action" onClick={scanNow} disabled={scanBusy}><RefreshCw size={14} className={scanBusy?'spin':''}/> {scanBusy?'Scanning…':'Scan Retailers'}</button></div></section>
   {scanMessage&&<div className="scan-message">{scanMessage}</div>}<div className="search-row"><label className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search deals"/></label><button className={`filter-btn ${activeCount?'has-filters':''}`} onClick={()=>setFiltersOpen(true)}><SlidersHorizontal size={18}/> Filters {activeCount?`(${activeCount})`:''}</button></div>
   <div className="chip-scroll">{categories.map(c=><button key={c} onClick={()=>{setCategory(c);setSubcategory('All')}} className={`chip ${category===c?'selected':''}`}>{c}</button>)}</div>
   {subs.length>0&&<div className="chip-scroll subcategory-row"><button onClick={()=>setSubcategory('All')} className={`chip small ${subcategory==='All'?'selected':''}`}>All {category}</button>{subs.map(s=><button key={s} onClick={()=>setSubcategory(s)} className={`chip small ${subcategory===s?'selected':''}`}>{s}</button>)}</div>}
   <div className="chip-scroll secondary">{quick.map(c=><button key={c} onClick={()=>toggleQuick(c)} className={`chip small ${quickFilters.includes(c)?'selected':''}`}>{c}</button>)}</div>
   <div className="sort-tabs">{sortTabs.map(t=><button key={t} onClick={()=>setSortBy(t)} className={sortBy===t?'selected':''}>{t}</button>)}</div>
   {loading&&<div className="empty-panel"><h3>Loading verified deals…</h3></div>}{error&&<div className="error-note">{error}</div>}
   {!loading&&<section className="deal-list">{filtered.map(d=><div key={d.id} className="deal-card-wrap"><DealCard deal={d} watched={watched.has(d.productId)} onToggleWatch={toggleWatch}/><button className="deal-reject-btn" onClick={()=>setFeedbackDeal(d)} title="Remove inaccurate or unwanted deal"><EyeOff size={15}/> Not Accurate</button></div>)}{filtered.length===0&&<div className="empty-panel"><h3>{allDeals.length?'No deals match these filters':'No live verified deals yet'}</h3><p>{allDeals.length?'Clear or change a filter.':'The app will only show real retailer products after exact-size inventory has been verified.'}</p>{allDeals.length>0&&<button className="secondary-btn" onClick={resetAll}>Clear filters</button>}</div>}</section>}
   {feedbackDeal&&<div className="modal-backdrop" onClick={()=>setFeedbackDeal(null)}><section className="filter-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="filter-sheet-head"><div><h2>Remove this deal?</h2><p>Tell the app why so future scans get smarter.</p></div><button className="sheet-close" onClick={()=>setFeedbackDeal(null)}><X size={20}/></button></div><div className="feedback-reasons">{[['size_unavailable','Size unavailable'],['price_wrong','Price / sale is wrong'],['sale_ended','Sale ended'],['bad_link','Bad product link'],['wrong_product','Wrong / men’s product'],['not_style',"Not Hollie's style"],['already_owns_similar','Already owns / too similar'],['other','Other']].map(([key,label])=><button key={key} className="secondary-btn feedback-reason" onClick={()=>rejectDeal(key)}>{label}</button>)}</div></section></div>}
   {filtersOpen&&<div className="modal-backdrop" onClick={()=>setFiltersOpen(false)}><section className="filter-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="filter-sheet-head"><div><h2>Filters</h2><p>Narrow Hollie's verified deals.</p></div><button className="sheet-close" onClick={()=>setFiltersOpen(false)}><X size={20}/></button></div>
    <div className="filter-group"><label>Item type</label><select value={category} onChange={e=>{setCategory(e.target.value);setSubcategory('All')}}>{categories.map(c=><option key={c}>{c}</option>)}</select></div>
    {subs.length>0&&<div className="filter-group"><label>Subcategory</label><select value={subcategory} onChange={e=>setSubcategory(e.target.value)}><option>All</option>{subs.map(s=><option key={s}>{s}</option>)}</select></div>}
    <div className="filter-grid-2"><div className="filter-group"><label>Season</label><select value={season} onChange={e=>setSeason(e.target.value)}>{seasons.map(x=><option key={x}>{x}</option>)}</select></div><div className="filter-group"><label>Use</label><select value={occasion} onChange={e=>setOccasion(e.target.value)}><option>Any</option>{occasions.map(x=><option key={x}>{x}</option>)}</select></div></div>
    <div className="filter-group"><label>Minimum discount</label><div className="discount-options">{[0,25,35,50,70].map(n=><button key={n} onClick={()=>setMinDiscount(n)} className={minDiscount===n?'selected':''}>{n?`${n}%+`:'Any'}</button>)}</div></div><div className="sheet-actions"><button className="secondary-btn" onClick={resetAll}>Reset</button><button className="primary-btn" onClick={()=>setFiltersOpen(false)}>Show {filtered.length} Deals</button></div>
   </section></div>}
 </main>
}
