import { useEffect, useMemo, useState } from 'react'
import { SlidersHorizontal, Check, Search, X, RefreshCw } from 'lucide-react'
import Header from '../components/Header'
import DealCard from '../components/DealCard'
import { categories, taxonomy, seasons, occasions } from '../lib/taxonomy'
import { loadLiveDeals, formatScanTime } from '../lib/deals'
import { supabase } from '../lib/supabase'
import { runRetailerScan } from '../lib/productImport'
import { useAuth } from '../context/AuthContext'

const quick=['70%+ Off','New','Verified Size','Church','Everyday','Fall','Lowest Seen']; const sortTabs=['Best for Hollie','Deepest Discounts','Newest']
export default function Deals(){
 const {session}=useAuth(); const [scanBusy,setScanBusy]=useState(false); const [scanMessage,setScanMessage]=useState(''); const [allDeals,setAllDeals]=useState([]); const [lastScan,setLastScan]=useState(null); const [watched,setWatched]=useState(new Set()); const [profileId,setProfileId]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 const [category,setCategory]=useState('All'),[subcategory,setSubcategory]=useState('All'),[quickFilters,setQuickFilters]=useState([]),[sortBy,setSortBy]=useState('Best for Hollie'),[q,setQ]=useState(''),[filtersOpen,setFiltersOpen]=useState(false),[season,setSeason]=useState('Any'),[occasion,setOccasion]=useState('Any'),[minDiscount,setMinDiscount]=useState(0)
 const scanNow=async()=>{setScanBusy(true);setScanMessage('Checking retailers…');try{const r=await runRetailerScan();const checked=(r.summary||[]).reduce((a,x)=>a+(x.checked||0),0),found=(r.summary||[]).reduce((a,x)=>a+(x.deals||0),0);setScanMessage(`Scan complete: ${checked} products checked, ${found} qualifying deals found.`);await load()}catch(e){setScanMessage(e.message)}finally{setScanBusy(false)}}
 const load=async()=>{setLoading(true);setError(''); const {deals,lastScan,error}=await loadLiveDeals(session?.user?.id); if(error)setError(error.message);setAllDeals(deals);setLastScan(lastScan)
   if(session?.user?.id){const [{data:p},{data:w}]=await Promise.all([supabase.from('fh_profiles').select('id').eq('owner_user_id',session.user.id).single(),supabase.from('fh_watchlist').select('product_id').eq('owner_user_id',session.user.id).eq('active',true)]);setProfileId(p?.id||null);setWatched(new Set((w||[]).map(x=>x.product_id)))} setLoading(false)}
 useEffect(()=>{load()},[session?.user?.id])
 const toggleQuick=n=>setQuickFilters(p=>p.includes(n)?p.filter(x=>x!==n):[...p,n]); const resetAll=()=>{setCategory('All');setSubcategory('All');setQuickFilters([]);setSeason('Any');setOccasion('Any');setMinDiscount(0);setQ('')}
 const filtered=useMemo(()=>{let rows=allDeals.filter(d=>{if(category!=='All'&&d.category!==category)return false;if(subcategory!=='All'&&d.subcategory!==subcategory)return false;if(season!=='Any'&&!(d.season||[]).includes(season))return false;if(occasion!=='Any'&&!(d.occasion||[]).includes(occasion))return false;if(d.discount<minDiscount)return false;if(q&&!`${d.store} ${d.name} ${d.category} ${d.subcategory}`.toLowerCase().includes(q.toLowerCase()))return false;if(quickFilters.includes('70%+ Off')&&d.discount<70)return false;if(quickFilters.includes('New')&&!d.newDeal)return false;if(quickFilters.includes('Verified Size')&&!d.verified)return false;if(quickFilters.includes('Church')&&!d.occasion.includes('Church'))return false;if(quickFilters.includes('Everyday')&&!d.occasion.includes('Everyday'))return false;if(quickFilters.includes('Fall')&&!d.season.includes('Fall'))return false;if(quickFilters.includes('Lowest Seen')&&!d.lowestSeen)return false;return true}); if(sortBy==='Deepest Discounts')rows=[...rows].sort((a,b)=>b.discount-a.discount);else if(sortBy==='Newest')rows=[...rows].sort((a,b)=>Number(b.newDeal)-Number(a.newDeal)||b.discount-a.discount);else rows=[...rows].sort((a,b)=>(b.match||0)-(a.match||0)||b.discount-a.discount);return rows},[allDeals,category,subcategory,season,occasion,minDiscount,q,quickFilters,sortBy])
 const toggleWatch=async deal=>{if(!session?.user?.id||!profileId||!deal.productId)return; if(watched.has(deal.productId)){await supabase.from('fh_watchlist').update({active:false}).eq('owner_user_id',session.user.id).eq('product_id',deal.productId);setWatched(p=>{const n=new Set(p);n.delete(deal.productId);return n})}else{const {data:existing}=await supabase.from('fh_watchlist').select('id').eq('owner_user_id',session.user.id).eq('product_id',deal.productId).maybeSingle();let error;if(existing?.id){({error}=await supabase.from('fh_watchlist').update({variant_id:deal.variantId||null,watch_price:deal.sale,watch_size:deal.size,price_drop_alert:true,restock_alert:true,lowest_price_alert:true,active:true}).eq('id',existing.id))}else{({error}=await supabase.from('fh_watchlist').insert({owner_user_id:session.user.id,profile_id:profileId,product_id:deal.productId,variant_id:deal.variantId||null,watch_price:deal.sale,watch_size:deal.size,price_drop_alert:true,restock_alert:true,lowest_price_alert:true,active:true}))}if(!error)setWatched(p=>new Set([...p,deal.productId]))}}
 const activeCount=quickFilters.length+(category!=='All')+(subcategory!=='All')+(season!=='Any')+(occasion!=='Any')+(minDiscount?1:0); const subs=category==='All'?[]:(taxonomy[category]||[])
 return <main className="page"><Header title="Deals" subtitle="Verified discounts in Hollie's exact size."/>
   <section className="update-strip"><div><Check size={16}/><strong>Verified feed</strong> · {formatScanTime(lastScan)}</div><div className="scan-actions"><button className="text-action" onClick={load}><RefreshCw size={14}/> Refresh</button><button className="text-action" onClick={scanNow} disabled={scanBusy}><RefreshCw size={14} className={scanBusy?'spin':''}/> {scanBusy?'Scanning…':'Scan Retailers'}</button></div></section>
   {scanMessage&&<div className="scan-message">{scanMessage}</div>}<div className="search-row"><label className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search deals"/></label><button className={`filter-btn ${activeCount?'has-filters':''}`} onClick={()=>setFiltersOpen(true)}><SlidersHorizontal size={18}/> Filters {activeCount?`(${activeCount})`:''}</button></div>
   <div className="chip-scroll">{categories.map(c=><button key={c} onClick={()=>{setCategory(c);setSubcategory('All')}} className={`chip ${category===c?'selected':''}`}>{c}</button>)}</div>
   {subs.length>0&&<div className="chip-scroll subcategory-row"><button onClick={()=>setSubcategory('All')} className={`chip small ${subcategory==='All'?'selected':''}`}>All {category}</button>{subs.map(s=><button key={s} onClick={()=>setSubcategory(s)} className={`chip small ${subcategory===s?'selected':''}`}>{s}</button>)}</div>}
   <div className="chip-scroll secondary">{quick.map(c=><button key={c} onClick={()=>toggleQuick(c)} className={`chip small ${quickFilters.includes(c)?'selected':''}`}>{c}</button>)}</div>
   <div className="sort-tabs">{sortTabs.map(t=><button key={t} onClick={()=>setSortBy(t)} className={sortBy===t?'selected':''}>{t}</button>)}</div>
   {loading&&<div className="empty-panel"><h3>Loading verified deals…</h3></div>}{error&&<div className="error-note">{error}</div>}
   {!loading&&!error&&<section className="deal-list">{filtered.map(d=><DealCard key={d.id} deal={d} watched={watched.has(d.productId)} onToggleWatch={toggleWatch}/>)}{filtered.length===0&&<div className="empty-panel"><h3>{allDeals.length?'No deals match these filters':'No live verified deals yet'}</h3><p>{allDeals.length?'Clear or change a filter.':'The app will only show real retailer products after exact-size inventory has been verified.'}</p>{allDeals.length>0&&<button className="secondary-btn" onClick={resetAll}>Clear filters</button>}</div>}</section>}
   {filtersOpen&&<div className="modal-backdrop" onClick={()=>setFiltersOpen(false)}><section className="filter-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="filter-sheet-head"><div><h2>Filters</h2><p>Narrow Hollie's verified deals.</p></div><button className="sheet-close" onClick={()=>setFiltersOpen(false)}><X size={20}/></button></div>
    <div className="filter-group"><label>Item type</label><select value={category} onChange={e=>{setCategory(e.target.value);setSubcategory('All')}}>{categories.map(c=><option key={c}>{c}</option>)}</select></div>
    {subs.length>0&&<div className="filter-group"><label>Subcategory</label><select value={subcategory} onChange={e=>setSubcategory(e.target.value)}><option>All</option>{subs.map(s=><option key={s}>{s}</option>)}</select></div>}
    <div className="filter-grid-2"><div className="filter-group"><label>Season</label><select value={season} onChange={e=>setSeason(e.target.value)}>{seasons.map(x=><option key={x}>{x}</option>)}</select></div><div className="filter-group"><label>Use</label><select value={occasion} onChange={e=>setOccasion(e.target.value)}><option>Any</option>{occasions.map(x=><option key={x}>{x}</option>)}</select></div></div>
    <div className="filter-group"><label>Minimum discount</label><div className="discount-options">{[0,50,60,70].map(n=><button key={n} onClick={()=>setMinDiscount(n)} className={minDiscount===n?'selected':''}>{n?`${n}%+`:'Any'}</button>)}</div></div><div className="sheet-actions"><button className="secondary-btn" onClick={resetAll}>Reset</button><button className="primary-btn" onClick={()=>setFiltersOpen(false)}>Show {filtered.length} Deals</button></div>
   </section></div>}
 </main>
}
