import { useEffect, useMemo, useState } from 'react'; import { UserRound, Store, Gift, Bell, Palette, ShieldCheck, ChevronRight, Plus, Save, Trash2, LogOut, ArrowLeft, Info, Copy, Activity, PlayCircle } from 'lucide-react'; import { useLocation, useNavigate } from 'react-router-dom'; import Header from '../components/Header'; import { supabase } from '../lib/supabase'; import { useAuth } from '../context/AuthContext'
const sections=[['fit',UserRound,'Fit Profile','Sizes and store-specific fit'],['retailers',Store,'Retailers','Turn monitored stores on or off'],['rewards',Gift,'Rewards Wallet','Store cash, points and promo codes'],['notifications',Bell,'Notifications','Immediate and digest preferences'],['style',Palette,'Style Preferences','What Hollie likes and avoids'],['health',Activity,'Deal Scanner & Health','Retailer status, scan history and diagnostics'],['privacy',ShieldCheck,'Privacy','Private account controls'],['about',Info,'About For Hollie','Version, deal engine and diagnostics']]
export default function Settings(){const{session,signOut}=useAuth();const loc=useLocation();const nav=useNavigate();const param=new URLSearchParams(loc.search).get('section');const[health,setHealth]=useState([]),[meta,setMeta]=useState({}),[systemResult,setSystemResult]=useState(null),[active,setActive]=useState(param||null),[profileId,setProfileId]=useState(null),[sizes,setSizes]=useState([]),[retailers,setRetailers]=useState([]),[rewards,setRewards]=useState([]),[prefs,setPrefs]=useState({notifications:{immediate:true,digest:true,push:true,email:true},style:{modest:true,youthful:true,avoid_boxy:true,avoid_bright:false}}),[rewardForm,setRewardForm]=useState({retailer_id:'',name:'',reward_type:'store_cash',cash_value:'',points_balance:'',promo_code:'',expires_at:''}),[msg,setMsg]=useState('')
 const load=async()=>{if(!session?.user?.id)return;const{data:p}=await supabase.from('fh_profiles').select('id').eq('owner_user_id',session.user.id).single();setProfileId(p?.id||null);if(!p?.id)return;const[{data:s},{data:r},{data:rp},{data:a}]=await Promise.all([supabase.from('fh_size_profiles').select('*').eq('profile_id',p.id).order('category'),supabase.from('fh_retailers').select('id,name,slug').order('scan_priority'),supabase.from('fh_retailer_preferences').select('retailer_id,enabled').eq('profile_id',p.id),supabase.from('fh_rewards').select('*').eq('owner_user_id',session.user.id).eq('status','active').order('created_at',{ascending:false})]);const map=new Map((rp||[]).map(x=>[x.retailer_id,x.enabled]));setSizes(s||[]);setRetailers((r||[]).map(x=>({...x,enabled:map.has(x.id)?map.get(x.id):true})));setRewards(a||[]);const{data:ap}=await supabase.from('fh_app_settings').select('notifications,style_preferences').eq('owner_user_id',session.user.id).maybeSingle();if(ap)setPrefs({notifications:ap.notifications||prefs.notifications,style:ap.style_preferences||prefs.style})}
 const loadHealth=async()=>{const [{data:r},{data:sc},{data:m},{data:q}]=await Promise.all([supabase.from('fh_retailers').select('id,name,slug,scan_status,last_scan_at,last_successful_scan_at').order('scan_priority'),supabase.from('fh_retailer_scans').select('retailer_id,finished_at,status,products_checked,deals_found,new_deals,errors').order('finished_at',{ascending:false}).limit(80),supabase.from('fh_system_meta').select('key,value'),supabase.from('fh_deal_quarantine').select('retailer_id').eq('active',true)]);setMeta(Object.fromEntries((m||[]).map(x=>[x.key,x.value])));const latest=new Map();for(const x of sc||[])if(!latest.has(x.retailer_id))latest.set(x.retailer_id,x);const qc={};for(const x of q||[])qc[x.retailer_id]=(qc[x.retailer_id]||0)+1;setHealth((r||[]).map(x=>({...x,scan:latest.get(x.id),quarantine:qc[x.id]||0}))) }
 const runSystemCheck=async()=>{const checks=[];const a=await supabase.from('fh_system_meta').select('value').eq('key','schema_version').maybeSingle();checks.push(['Database schema',a.data?.value==='8',a.error?.message||`v${a.data?.value||'missing'}`]);const b=await supabase.from('fh_watchlist').select('id').limit(1);checks.push(['Watchlist access',!b.error,b.error?.message||'OK']);const c=await supabase.from('fh_deal_feedback').select('id').limit(1);checks.push(['Feedback access',!c.error,c.error?.message||'OK']);const d=await supabase.from('fh_retailer_scans').select('id').limit(1);checks.push(['Scanner records',!d.error,d.error?.message||'OK']);setSystemResult(checks)}
 useEffect(()=>{load()},[session?.user?.id]);useEffect(()=>{setActive(param||null);if(param==='health')loadHealth()},[param])
 const saveSize=async row=>{const{error}=await supabase.from('fh_size_profiles').update({size_primary:row.size_primary,size_secondary:row.size_secondary,bra_band:row.bra_band||null,bra_cup:row.bra_cup||null,shoe_min:row.shoe_min||null,shoe_max:row.shoe_max||null}).eq('id',row.id);setMsg(error?error.message:'Size saved.')}
 const toggleRetailer=async r=>{const next=!r.enabled;const{error}=await supabase.from('fh_retailer_preferences').upsert({owner_user_id:session.user.id,profile_id:profileId,retailer_id:r.id,enabled:next},{onConflict:'profile_id,retailer_id'});if(!error)setRetailers(p=>p.map(x=>x.id===r.id?{...x,enabled:next}:x))}
 const addReward=async e=>{e.preventDefault();const payload={owner_user_id:session.user.id,profile_id:profileId,retailer_id:rewardForm.retailer_id||null,reward_type:rewardForm.reward_type,name:rewardForm.name,cash_value:rewardForm.cash_value?Number(rewardForm.cash_value):null,points_balance:rewardForm.points_balance?Number(rewardForm.points_balance):null,promo_code:rewardForm.promo_code||null,expires_at:rewardForm.expires_at||null,status:'active'};const{error}=await supabase.from('fh_rewards').insert(payload);if(error)setMsg(error.message);else{setRewardForm({retailer_id:'',name:'',reward_type:'store_cash',cash_value:'',points_balance:'',promo_code:'',expires_at:''});load()}}
 const removeReward=async id=>{await supabase.from('fh_rewards').update({status:'redeemed'}).eq('id',id).eq('owner_user_id',session.user.id);setRewards(p=>p.filter(x=>x.id!==id))}
 const savePrefs=async()=>{const{error}=await supabase.from('fh_app_settings').upsert({owner_user_id:session.user.id,profile_id:profileId,notifications:prefs.notifications,style_preferences:prefs.style},{onConflict:'owner_user_id'});setMsg(error?error.message:'Preferences saved.')}
 if(!active)return <main className="page"><Header title="Settings" subtitle="Tune For Hollie without cluttering the main experience."/><section className="settings-list">{sections.map(([key,Icon,title,sub])=><button className="settings-row" key={key} onClick={()=>nav(`/settings?section=${key}`)}><span className="settings-icon"><Icon size={19}/></span><span><strong>{title}</strong><small>{sub}</small></span><ChevronRight size={18}/></button>)}</section></main>
 const title=sections.find(x=>x[0]===active)?.[2]||'Settings'; return <main className="page"><Header title={title}/><button className="back-link" onClick={()=>nav('/settings')}><ArrowLeft size={17}/> Settings</button>{msg&&<div className="status-note">{msg}</div>}
 {active==='fit'&&<section className="settings-panel"><p className="panel-help">Edit Hollie’s sizes any time. These are used by the deal verifier.</p>{sizes.map((s,i)=><div className="size-row" key={s.id}><strong>{s.category.replaceAll('_',' ')}</strong><input value={s.size_primary||''} onChange={e=>setSizes(p=>p.map((x,j)=>j===i?{...x,size_primary:e.target.value}:x))}/><input value={s.size_secondary||''} placeholder="Secondary / store note" onChange={e=>setSizes(p=>p.map((x,j)=>j===i?{...x,size_secondary:e.target.value}:x))}/><button className="mini-btn" onClick={()=>saveSize(s)}><Save size={14}/> Save</button></div>)}</section>}
 {active==='retailers'&&<section className="settings-panel"><p className="panel-help">Disabled stores stay out of personalized monitoring.</p>{retailers.map(r=><button className="toggle-row" key={r.id} onClick={()=>toggleRetailer(r)}><span>{r.name}</span><span className={`switch ${r.enabled?'on':''}`}><i/></span></button>)}</section>}
 {active==='rewards'&&<section className="settings-panel"><form className="reward-form" onSubmit={addReward}><div className="form-grid"><label>Store<select value={rewardForm.retailer_id} onChange={e=>setRewardForm(p=>({...p,retailer_id:e.target.value}))}><option value="">Choose store</option>{retailers.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Reward name<input required value={rewardForm.name} onChange={e=>setRewardForm(p=>({...p,name:e.target.value}))} placeholder="Torrid Cash"/></label></div><div className="form-grid"><label>Cash value<input type="number" min="0" step="0.01" value={rewardForm.cash_value} onChange={e=>setRewardForm(p=>({...p,cash_value:e.target.value}))}/></label><label>Points<input type="number" min="0" value={rewardForm.points_balance} onChange={e=>setRewardForm(p=>({...p,points_balance:e.target.value}))}/></label></div><div className="form-grid"><label>Promo code<input value={rewardForm.promo_code} onChange={e=>setRewardForm(p=>({...p,promo_code:e.target.value}))}/></label><label>Expires<input type="date" value={rewardForm.expires_at} onChange={e=>setRewardForm(p=>({...p,expires_at:e.target.value}))}/></label></div><button className="primary-btn"><Plus size={16}/> Add Reward</button></form><div className="reward-list">{rewards.map(r=><div className="reward-card" key={r.id}><div><strong>{r.name}</strong><span>{r.cash_value!=null?`$${Number(r.cash_value).toFixed(2)}`:r.points_balance!=null?`${r.points_balance} points`:r.promo_code||'Reward'}</span>{r.expires_at&&<small>Expires {r.expires_at}</small>}</div><button className="mini-btn" onClick={()=>removeReward(r.id)}><Trash2 size={14}/> Redeemed</button></div>)}</div></section>}
 {active==='notifications'&&<section className="settings-panel">{Object.entries(prefs.notifications).map(([k,v])=><button className="toggle-row" key={k} onClick={()=>setPrefs(p=>({...p,notifications:{...p.notifications,[k]:!v}}))}><span>{k.charAt(0).toUpperCase()+k.slice(1)}</span><span className={`switch ${v?'on':''}`}><i/></span></button>)}<button className="primary-btn settings-save" onClick={savePrefs}><Save size={16}/> Save Notifications</button></section>}
 {active==='style'&&<section className="settings-panel">{Object.entries(prefs.style).map(([k,v])=><button className="toggle-row" key={k} onClick={()=>setPrefs(p=>({...p,style:{...p.style,[k]:!v}}))}><span>{k.replaceAll('_',' ')}</span><span className={`switch ${v?'on':''}`}><i/></span></button>)}<button className="primary-btn settings-save" onClick={savePrefs}><Save size={16}/> Save Style Preferences</button></section>}


 {active==='health'&&<section className="settings-panel"><div className="health-summary"><strong>V8 retailer health</strong><span>{health.filter(x=>x.scan_status==='success').length} healthy · {health.filter(x=>x.scan_status!=='success').length} need attention</span></div><button className="primary-btn settings-save" onClick={runSystemCheck}><PlayCircle size={16}/> Run System Check</button>{systemResult&&<div className="system-checks">{systemResult.map(([n,ok,d])=><div className={`health-row ${ok?'ok':'bad'}`} key={n}><strong>{ok?'✓':'!'} {n}</strong><small>{d}</small></div>)}</div>}<div className="health-list">{health.map(r=>{const diag=Array.isArray(r.scan?.errors)?r.scan.errors.find(x=>x?.type==='diagnostic'):null;return <div className="health-card" key={r.id}><div className="health-card-head"><strong>{r.name}</strong><span className={`health-pill ${r.scan_status==='success'?'ok':'bad'}`}>{r.scan_status==='success'?'Healthy':'Attention'}</span></div><small>Last scan: {r.scan?.finished_at?new Date(r.scan.finished_at).toLocaleString():'Never'}</small><div className="health-metrics"><span>{r.scan?.products_checked||0}<small>checked</small></span><span>{diag?.sizeVerified||0}<small>sizes verified</small></span><span>{r.scan?.deals_found||0}<small>deals</small></span><span>{r.quarantine}<small>quarantined</small></span></div></div>})}</div></section>}

 {active==='about'&&<section className="settings-panel"><div className="version-card"><div><small>APP VERSION</small><strong>8.0.0</strong></div><div><small>DEAL ENGINE</small><strong>V8 Accurate Broad Feed</strong></div><div><small>BUILD</small><strong>2026.09.15</strong></div><div><small>SCANNER RULES</small><strong>V8 Two-Stage Validation + Retailer Health</strong></div><div><small>DATABASE</small><strong>V8 Schema</strong></div></div><button className="secondary-btn settings-save" onClick={()=>navigator.clipboard?.writeText('For Hollie 8.0.0 | Deal Engine V8 Accurate Broad Feed | Build 2026.09.15 | Scanner V8 | DB V8')}><Copy size={16}/> Copy Diagnostics</button><p className="app-version-footer">For Hollie · v8.0.0 · build 2026.09.15</p></section>}
 {active==='privacy'&&<section className="settings-panel"><div className="privacy-card"><ShieldCheck/><div><strong>Private single-user app</strong><p>For Hollie data is protected by your Supabase login and row-level security.</p></div></div><button className="secondary-btn danger settings-save" onClick={async()=>{await signOut();nav('/')}}><LogOut size={16}/> Sign Out</button></section>}
 </main>}
