import { useEffect, useMemo, useState } from 'react'
import { Search, Plus, SlidersHorizontal, PackageCheck, Truck, ImageOff, Pencil, CheckCircle2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import Header from '../components/Header'
import { supabase, supabaseConfigured } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
import { categories } from '../lib/taxonomy'
import '../wardrobe.css'
function ItemImage({item}){const[failed,setFailed]=useState(false);return !item.image_url||failed?<div className="wardrobe-placeholder"><ImageOff size={26}/><span>{item.category||'Wardrobe'}</span></div>:<img src={item.image_url} alt={item.custom_name||'Wardrobe item'} onError={()=>setFailed(true)}/>}
export default function Wardrobe(){const{session}=useAuth();const[items,setItems]=useState([]),[loading,setLoading]=useState(true),[category,setCategory]=useState('All'),[q,setQ]=useState(''),[error,setError]=useState(''),[filtersOpen,setFiltersOpen]=useState(false),[status,setStatus]=useState('all'),[sort,setSort]=useState('newest')
 const load=async()=>{if(!supabaseConfigured||!session?.user?.id){setLoading(false);return}const{data,error}=await supabase.from('fh_wardrobe_items').select(`id,custom_name,image_url,category,subcategory,brand,color,size,purchase_price,regular_price,purchase_date,status,product_url,notes,created_at,retailer:fh_retailers(name)`).eq('owner_user_id',session.user.id).in('status',['owned','on_the_way']).order('created_at',{ascending:false});if(error)setError(error.message);else setItems(data||[]);setLoading(false)};useEffect(()=>{load()},[session?.user?.id])
 const filtered=useMemo(()=>{let a=items.filter(i=>(category==='All'||i.category===category)&&(status==='all'||i.status===status)&&(!q||`${i.custom_name||''} ${i.brand||''} ${i.color||''} ${i.subcategory||''}`.toLowerCase().includes(q.toLowerCase())));if(sort==='name')a=[...a].sort((x,y)=>(x.custom_name||'').localeCompare(y.custom_name||''));if(sort==='price')a=[...a].sort((x,y)=>(Number(y.purchase_price)||0)-(Number(x.purchase_price)||0));return a},[items,category,status,q,sort])
 const markOwned=async id=>{const{error}=await supabase.from('fh_wardrobe_items').update({status:'owned'}).eq('id',id).eq('owner_user_id',session.user.id);if(!error)setItems(p=>p.map(i=>i.id===id?{...i,status:'owned'}:i))}
 return <main className="page"><Header title="Wardrobe" subtitle="Hollie's real closet—no demo products."/><div className="wardrobe-summary"><div><strong>{items.length}</strong><span>Tracked items</span></div><div><strong>{items.filter(x=>x.status==='on_the_way').length}</strong><span>On the way</span></div><div><strong>{items.filter(x=>x.status==='owned').length}</strong><span>Owned</span></div></div>
 <div className="search-row"><label className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search wardrobe"/></label><button className={`filter-btn ${filtersOpen?'has-filters':''}`} onClick={()=>setFiltersOpen(v=>!v)}><SlidersHorizontal size={18}/> Filters</button></div>
 {filtersOpen&&<div className="inline-filter-panel"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All tracked</option><option value="owned">Owned</option><option value="on_the_way">On the way</option></select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Newest added</option><option value="name">Name</option><option value="price">Price paid</option></select></label></div>}
 <div className="chip-scroll">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`chip ${category===c?'selected':''}`}>{c}</button>)}</div><Link to="/wardrobe/add" className="add-btn wardrobe-add-btn"><Plus size={17}/> Add item</Link>
 {loading&&<div className="empty-panel"><h3>Loading wardrobe…</h3></div>}{error&&<div className="error-note">{error}</div>}{!loading&&!error&&filtered.length===0&&<div className="empty-panel"><h3>{items.length?'No items match this filter':'Start Hollie’s updated wardrobe'}</h3><p>{items.length?'Try another filter.':'Add new purchases here as you buy them.'}</p><Link to="/wardrobe/add" className="primary-btn"><Plus size={16}/> Add item</Link></div>}
 <section className="wardrobe-grid">{filtered.map(item=><article className="wardrobe-card" key={item.id}><div className="wardrobe-image-wrap"><ItemImage item={item}/><span className={`owned-status ${item.status}`}>{item.status==='on_the_way'?<><Truck size={13}/> On the way</>:<><PackageCheck size={13}/> Owned</>}</span></div><div className="wardrobe-body"><span className="eyebrow">{item.retailer?.name||item.brand||'Wardrobe'}</span><h3>{item.custom_name||'Untitled item'}</h3><p>{[item.color,item.size?`Size ${item.size}`:null].filter(Boolean).join(' · ')}</p><div className="wardrobe-meta">{item.purchase_price!=null&&<span>${Number(item.purchase_price).toFixed(2)} paid</span>}{item.subcategory&&<span>{item.subcategory}</span>}</div><div className="card-actions"><Link to={`/wardrobe/${item.id}`} className="mini-btn"><Pencil size={14}/> Edit</Link>{item.status==='on_the_way'&&<button className="mini-btn" onClick={()=>markOwned(item.id)}><CheckCircle2 size={14}/> Received</button>}{item.product_url&&<a className="mini-btn" href={item.product_url} target="_blank" rel="noreferrer">Retailer</a>}</div></div></article>)}</section>
 </main>}
